export const BEARER_TOKEN: any = `TEST-SK-VRVPJFFZ-Y3AEFATJ-GNQ6Q9E2-Q4R2FXRH`;
export const API_KEY:any = `TEST-AK-9RR7X6VU-M6AFCMCD-E4A8E2ER-LU93WGQT`;
export const ADMIN_ACCOUNT:any = `AC_BXLM6XH7EBD`;

// ARCHITECTURE IMPLEMENTATION
// ONRAMPING  : METHOD 1  : CARD
// ONRAMPING  : METHOD 2  : BANK
// OFFRAMPING : METHOD 1 : CARD
// OFFRAMPING : METHOD 1 : BANK
// PAST HISTORY of ORDERS
